import { useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { BarChart3, Bell, Boxes, ChevronRight, FileKey2, FileText, LayoutDashboard, LogOut, Menu, MessageSquare, Palette, PlaySquare, Plus, RefreshCw, Search, ShieldCheck, SlidersHorizontal, Trash2, UserCog, Users, WalletCards, X, Zap } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { adminAdjustTokens, adminDeleteCollectionItem, adminListCollection, adminListServices, adminListTransactions, adminListUsers, adminSaveCollectionItem, adminSaveService, adminSaveSiteSettings, adminUpdateUser, type AdminUserRecord } from "@/lib/firebase";

type Panel = "overview" | "users" | "tokens" | "services" | "videos" | "transactions" | "announcements" | "cms" | "security" | "messages" | "licenses";
const nav: Array<[Panel, string, typeof LayoutDashboard]> = [
  ["overview", "Muhtasari", LayoutDashboard], ["users", "Watumiaji", Users], ["tokens", "Tokeni", WalletCards], ["services", "Huduma", Boxes], ["videos", "Video", PlaySquare], ["transactions", "Transactions", BarChart3], ["announcements", "Matangazo", Bell], ["cms", "Muonekano & CMS", Palette], ["security", "Usalama", ShieldCheck], ["messages", "Tuma ujumbe", MessageSquare], ["licenses", "Leseni", FileKey2],
];
const emptyService = { id: "", name: "", slug: "", description: "", icon: "file-badge", tokenCost: 2, isFree: false, isLocked: false, isVisible: true, category: "Huduma kuu", actionUrl: "", order: 0 };
const emptyVideo = { id: "", title: "", videoUrl: "", category: "Mafunzo", enabled: true, order: 0 };
const emptyAnnouncement = { id: "", title: "", body: "", enabled: true };
const emptyMessage = { subject: "", body: "", recipientId: "" };

function dateText(value: unknown) { if (!value) return "—"; const date = new Date(String(value)); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleString("sw-TZ"); }
function safeError(error: any) { return error?.code === "permission-denied" ? "Huna ruhusa ya kufanya kitendo hiki." : "Imeshindikana kupata au kuhifadhi taarifa. Jaribu tena."; }
function Field({ label, value, onChange, type = "text", placeholder = "" }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <label className="control-field"><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>; }
function Empty({ text = "Hakuna data bado" }: { text?: string }) { return <div className="admin-empty">{text}</div>; }

export default function AdminDashboard() {
  const [location] = useLocation();
  const { user, firebaseUser, loading, logout, isAuthenticated } = useAuth();
  const [drawer, setDrawer] = useState(false);
  const [busy, setBusy] = useState(false);
  const [loadingData, setLoadingData] = useState(false);
  const [users, setUsers] = useState<(AdminUserRecord & { id: string })[]>([]);
  const [services, setServices] = useState<any[]>([]);
  const [transactions, setTransactions] = useState<any[]>([]);
  const [videos, setVideos] = useState<any[]>([]);
  const [announcements, setAnnouncements] = useState<any[]>([]);
  const [messages, setMessages] = useState<any[]>([]);
  const [licenses, setLicenses] = useState<any[]>([]);
  const [audit, setAudit] = useState<any[]>([]);
  const [search, setSearch] = useState("");
  const [selectedUser, setSelectedUser] = useState<(AdminUserRecord & { id: string }) | null>(null);
  const [tokenForm, setTokenForm] = useState({ userId: "", amount: 10, reason: "" });
  const [service, setService] = useState(emptyService);
  const [video, setVideo] = useState(emptyVideo);
  const [announcement, setAnnouncement] = useState(emptyAnnouncement);
  const [message, setMessage] = useState(emptyMessage);
  const [cms, setCms] = useState({ systemName: "$TEWARD TZ", eyebrow: "HUDUMA ZA MTANDAONI", headline: "Huduma zako, sehemu moja.", description: "", searchPlaceholder: "Tafuta huduma...", whatsapp: "", owner: "", footer: "", primaryColor: "#18b969", accentColor: "#6ea8fe" });
  const canManage = isAuthenticated && ["admin", "super_admin"].includes(user?.role ?? "");
  const isSuper = user?.role === "super_admin";
  const panel = (location.split("/admin/")[1] || "overview") as Panel;

  const refresh = async () => {
    if (!canManage) return;
    setLoadingData(true);
    try {
      const [u, s, t, v, a, m, l, logs] = await Promise.all([
        adminListUsers(), adminListServices(), adminListTransactions(), adminListCollection("tutorialVideos"), adminListCollection("announcements"), adminListCollection("messages"), adminListCollection("licenseTemplates"), adminListCollection("adminActions"),
      ]);
      setUsers(u); setServices(s); setTransactions(t); setVideos(v); setAnnouncements(a); setMessages(m); setLicenses(l); setAudit(logs);
    } catch (error) { toast.error(safeError(error)); } finally { setLoadingData(false); }
  };
  useEffect(() => { void refresh(); }, [canManage]);
  const run = async (action: () => Promise<unknown>, success: string) => { setBusy(true); try { await action(); await refresh(); toast.success(success); } catch (error) { toast.error(safeError(error)); } finally { setBusy(false); } };
  const visibleUsers = useMemo(() => users.filter((item) => `${item.name} ${item.phone} ${item.email} ${item.username}`.toLowerCase().includes(search.toLowerCase())), [users, search]);
  const totalIssued = transactions.filter((item) => Number(item.amount) > 0).reduce((sum, item) => sum + Number(item.amount), 0);
  const totalUsed = Math.abs(transactions.filter((item) => Number(item.amount) < 0).reduce((sum, item) => sum + Number(item.amount), 0));
  const totalRemaining = users.reduce((sum, item) => sum + Number(item.tokenBalance ?? 0), 0);
  const adminCount = users.filter((item) => ["admin", "super_admin"].includes(item.role)).length;
  const stats = [["Watumiaji wote", users.length, Users], ["Active Users", users.filter((item) => item.accountStatus !== "blocked").length, UserCog], ["Pending Users", users.filter((item) => item.verificationStatus === "pending").length, ShieldCheck], ["Admin Users", adminCount, ShieldCheck], ["Tokeni zilizotolewa", totalIssued, WalletCards], ["Tokeni zilizotumika", totalUsed, Zap], ["Tokeni zilizobaki", totalRemaining, WalletCards], ["Matumizi ya huduma", transactions.filter((item) => Number(item.amount) < 0).length, BarChart3]] as const;

  if (loading) return <main className="admin-guard"><RefreshCw className="spin" /> Inakagua ruhusa za admin...</main>;
  if (!canManage) return <main className="admin-guard"><ShieldCheck size={38} /><h2>Ukurasa huu ni wa admin pekee</h2><p>Ingia kwa akaunti yenye role ya admin au super_admin.</p><Link className="admin-primary" href="/">Rudi portal</Link></main>;
  const title = nav.find(([key]) => key === panel)?.[1] ?? "Muhtasari";
  return <div className="admin-app">
    <aside className={`admin-sidebar ${drawer ? "open" : ""}`}><div className="admin-brand"><div className="admin-brand-mark">$</div><div><strong>$TEWARD TZ</strong><small>CONTROL</small></div><button className="admin-close" onClick={() => setDrawer(false)}><X size={18} /></button></div><div className="admin-profile"><div className="admin-avatar">{String(user?.name ?? "AD").slice(0, 2).toUpperCase()}</div><div><strong>{user?.name ?? "Admin"}</strong><small>{String(user?.role ?? "admin").replace("_", " ").toUpperCase()}</small></div></div><nav className="admin-nav">{nav.map(([key, label, Icon]) => <Link key={key} href={key === "overview" ? "/admin" : `/admin/${key}`} className={panel === key ? "active" : ""} onClick={() => setDrawer(false)}><Icon size={17} /><span>{label}</span><ChevronRight size={14} /></Link>)}</nav><div className="admin-sidebar-bottom"><Link href="/"><ChevronRight size={15} /> Portal</Link><button onClick={() => void logout()}><LogOut size={15} /> Logout</button></div></aside>
    {drawer && <div className="admin-drawer-backdrop" onClick={() => setDrawer(false)} />}
    <section className="admin-content"><header className="admin-header"><button className="admin-menu" onClick={() => setDrawer(true)}><Menu size={21} /></button><div><span className="admin-kicker">$TEWARD TZ CONTROL</span><h1>{panel === "overview" ? "Muhtasari wa $TEWARD TZ" : title}</h1></div><div className="admin-header-actions"><span className="admin-auth-status"><i /> Firebase authenticated</span><button className="admin-icon-button" onClick={() => void refresh()} disabled={loadingData}><RefreshCw size={17} className={loadingData ? "spin" : ""} /></button><Link className="admin-portal-link" href="/">← Portal</Link></div></header>
      {loadingData && <div className="admin-loading">Inapakia data halisi kutoka Firestore...</div>}
      {panel === "overview" && <><div className="admin-stat-grid">{stats.map(([label, value, Icon]) => <div className="admin-stat-card" key={label}><div className="admin-stat-icon"><Icon size={18} /></div><span>{label}</span><strong>{value.toLocaleString()}</strong><small>Live Firestore data</small></div>)}</div><div className="admin-two-col"><section className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">HATUA ZA HARAKA</span><h2>Simamia mfumo</h2></div><SlidersHorizontal size={19} /></div><div className="quick-actions"><Link href="/admin/tokens"><Plus size={17} /> Ongeza tokeni</Link><Link href="/admin/services"><Plus size={17} /> Ongeza huduma</Link><Link href="/admin/announcements"><Plus size={17} /> Ongeza tangazo</Link></div></section><section className="admin-security-card"><div className="admin-card-heading"><div><span className="admin-kicker">USALAMA WA MFUMO</span><h2>Session salama</h2></div><ShieldCheck size={20} /></div><p><strong>{user?.name ?? "Admin"}</strong> · {String(user?.role ?? "admin").replace("_", " ").toUpperCase()}</p><small>Auth: Firebase Authentication · Last login: {dateText((user as any)?.lastLoginAt) !== "—" ? dateText((user as any)?.lastLoginAt) : "Session ya sasa"}</small></section></div><section className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">TRANSACTIONS ZA HIVI KARIBUNI</span><h2>Ledger</h2></div><Link href="/admin/transactions">Tazama zote</Link></div><TransactionTable rows={transactions.slice(0, 6)} /></section></>}
      {panel === "users" && <UsersPanel users={visibleUsers} search={search} setSearch={setSearch} onSelect={setSelectedUser} onRefresh={refresh} onRun={run} adminId={firebaseUser!.uid} isSuper={isSuper} busy={busy} />}
      {panel === "tokens" && <TokensPanel users={users} form={tokenForm} setForm={setTokenForm} onRun={run} adminId={firebaseUser!.uid} busy={busy} />}
      {panel === "services" && <ServicesPanel services={services} service={service} setService={setService} onRun={run} adminId={firebaseUser!.uid} busy={busy} />}
      {panel === "videos" && <CollectionPanel title="Video za Mafunzo" collectionName="tutorialVideos" rows={videos} form={video} setForm={setVideo} fields={[["title", "Title"], ["videoUrl", "Video URL"], ["category", "Category"], ["order", "Order"]]} onRun={run} adminId={firebaseUser!.uid} />}
      {panel === "transactions" && <section className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">AUDIT LEDGER</span><h2>Transactions</h2></div></div><TransactionTable rows={transactions} /></section>}
      {panel === "announcements" && <CollectionPanel title="Matangazo" collectionName="announcements" rows={announcements} form={announcement} setForm={setAnnouncement} fields={[["title", "Kichwa"], ["body", "Ujumbe"]]} onRun={run} adminId={firebaseUser!.uid} />}
      {panel === "cms" && <CmsPanel values={cms} setValues={setCms} onRun={run} adminId={firebaseUser!.uid} />}
      {panel === "security" && <SecurityPanel isSuper={isSuper} users={users} audit={audit} />}
      {panel === "messages" && <MessagesPanel users={users} form={message} setForm={setMessage} onRun={run} adminId={firebaseUser!.uid} />}
      {panel === "licenses" && <CollectionPanel title="Usimamizi wa Leseni" collectionName="licenseTemplates" rows={licenses} form={{ id: "", name: "", fileType: "", fileSize: "", status: "disabled" }} setForm={() => undefined} fields={[["name", "Template name"], ["fileType", "File type"], ["fileSize", "File size"]]} onRun={run} adminId={firebaseUser!.uid} readOnly />}
    </section>{selectedUser && <UserModal person={selectedUser} onClose={() => setSelectedUser(null)} />}</div>;
}

function UsersPanel({ users, search, setSearch, onSelect, onRun, adminId, isSuper, busy }: any) { return <section className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">FIRESTORE USERS</span><h2>Watumiaji</h2></div><span className="admin-count">{users.length}</span></div><div className="admin-search"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tafuta jina, simu au barua pepe..." /></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>MTUMIAJI</th><th>SIMU / EMAIL</th><th>ROLE</th><th>STATUS</th><th>VERIFICATION</th><th>TOKENI</th><th>ACTIONS</th></tr></thead><tbody>{users.map((person: any) => <tr key={person.id}><td><button className="user-cell" onClick={() => onSelect(person)}><span className="table-avatar">{String(person.name ?? "U").slice(0, 2).toUpperCase()}</span><span><strong>{person.name ?? "Bila jina"}</strong><small>{person.id.slice(0, 10)} · {dateText(person.createdAt)}</small></span></button></td><td>{person.phone || "—"}<small>{person.email || "—"}</small></td><td><span className="pill pill-blue">{person.role ?? "user"}</span></td><td><span className={`pill ${person.accountStatus === "blocked" ? "pill-red" : "pill-green"}`}>{person.accountStatus ?? "active"}</span></td><td><span className="pill">{person.verificationStatus ?? "pending"}</span></td><td><strong>{person.tokenBalance ?? 0}</strong><small>Received {person.totalTokensReceived ?? 0}</small></td><td><div className="table-actions"><button disabled={busy} onClick={() => onRun(() => adminUpdateUser(adminId, person.id, { verificationStatus: "approved" }), "User amethibitishwa.")}>Approve</button><button disabled={busy} onClick={() => onRun(() => adminUpdateUser(adminId, person.id, { accountStatus: person.accountStatus === "blocked" ? "active" : "blocked" }), person.accountStatus === "blocked" ? "User amefunguliwa." : "User amezuiwa.")}>{person.accountStatus === "blocked" ? "Fungua" : "Zuia"}</button>{isSuper && <button onClick={() => onRun(() => adminUpdateUser(adminId, person.id, { role: person.role === "admin" ? "user" : "admin" }), "Role imebadilishwa.")}>Role</button>}</div></td></tr>)}</tbody></table>{!users.length && <Empty />}</div></section>; }
function TokensPanel({ users, form, setForm, onRun, adminId, busy }: any) { return <div className="admin-two-col"><section className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">TOKEN LEDGER</span><h2>Usimamizi wa Tokeni</h2></div></div><label className="control-field"><span>Chagua mtumiaji</span><select value={form.userId} onChange={(event) => setForm({ ...form, userId: event.target.value })}><option value="">Chagua user — phone — balance</option>{users.map((item: any) => <option key={item.id} value={item.id}>{item.name ?? "Bila jina"} — {item.phone || item.email} — {item.tokenBalance ?? 0}</option>)}</select></label><Field label="Kiasi" type="number" value={form.amount} onChange={(value) => setForm({ ...form, amount: Number(value) })} /><label className="control-field"><span>Maelezo</span><textarea value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} placeholder="Bonus ya usajili" /></label><div className="form-actions"><button className="admin-primary" disabled={busy || !form.userId} onClick={() => onRun(() => adminAdjustTokens(adminId, form.userId, Math.abs(form.amount), form.reason || "Admin adjustment"), "Tokeni zimeongezwa.")}>+ Ongeza tokeni</button><button className="admin-danger" disabled={busy || !form.userId} onClick={() => onRun(() => adminAdjustTokens(adminId, form.userId, -Math.abs(form.amount), form.reason || "Admin adjustment"), "Tokeni zimepunguzwa.")}>− Punguza tokeni</button></div></section><section className="admin-card"><div className="admin-card-heading"><h2>Maelezo ya ledger</h2></div><p>Kila adjustment ina previousBalance, newBalance, adminId, reason, reference na timestamp. Hakuna password inayohifadhiwa au kuonyeshwa.</p><div className="ledger-note"><WalletCards size={20} /><span>Operations zote zinalindwa na Firestore Security Rules.</span></div></section></div>; }
function ServicesPanel({ services, service, setService, onRun, adminId, busy }: any) { return <section className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">SERVICE CMS</span><h2>Huduma</h2></div></div><div className="form-grid"><Field label="Jina" value={service.name} onChange={(value) => setService({ ...service, name: value })} /><Field label="Slug" value={service.slug} onChange={(value) => setService({ ...service, slug: value })} /><Field label="Icon" value={service.icon} onChange={(value) => setService({ ...service, icon: value })} /><Field label="Kundi" value={service.category} onChange={(value) => setService({ ...service, category: value })} /><Field label="Token cost" type="number" value={service.tokenCost} onChange={(value) => setService({ ...service, tokenCost: Number(value) })} /><Field label="Order" type="number" value={service.order} onChange={(value) => setService({ ...service, order: Number(value) })} /><Field label="Action URL" value={service.actionUrl} onChange={(value) => setService({ ...service, actionUrl: value })} /></div><label className="control-field"><span>Maelezo</span><textarea value={service.description} onChange={(event) => setService({ ...service, description: event.target.value })} /></label><div className="check-grid"><label><input type="checkbox" checked={service.isFree} onChange={(event) => setService({ ...service, isFree: event.target.checked })} /> Bure</label><label><input type="checkbox" checked={service.isLocked} onChange={(event) => setService({ ...service, isLocked: event.target.checked })} /> Locked</label><label><input type="checkbox" checked={service.isVisible} onChange={(event) => setService({ ...service, isVisible: event.target.checked })} /> Ionyeshe</label></div><button className="admin-primary" disabled={busy} onClick={() => onRun(() => adminSaveService(adminId, { ...service, id: undefined }, service.id || undefined), "Huduma imehifadhiwa.")}>Hifadhi huduma</button><div className="admin-list">{services.map((item: any) => <div className="admin-list-row" key={item.id}><div><strong>{item.name}</strong><small>{item.category} · {item.isFree ? "Bure" : `${item.tokenCost} tokeni`} · {item.isLocked ? "Locked" : "Active"}</small></div><div className="table-actions"><button onClick={() => setService({ ...emptyService, ...item })}>Hariri</button><button onClick={() => onRun(() => adminDeleteCollectionItem(adminId, "services", item.id), "Huduma imefutwa.")}><Trash2 size={14} /></button></div></div>)}</div></section>; }
function CollectionPanel({ title, collectionName, rows, form, setForm, fields, onRun, adminId, readOnly = false }: any) { return <section className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">FIRESTORE CMS</span><h2>{title}</h2></div></div>{!readOnly && <><div className="form-grid">{fields.map(([key, label]: string[]) => <Field key={key} label={label} value={form[key] ?? ""} onChange={(value) => setForm({ ...form, [key]: key === "order" ? Number(value) : value })} />)}</div><div className="check-grid"><label><input type="checkbox" checked={form.enabled !== false} onChange={(event) => setForm({ ...form, enabled: event.target.checked })} /> Imewezeshwa</label></div><button className="admin-primary" onClick={() => onRun(() => adminSaveCollectionItem(adminId, collectionName, { ...form, id: undefined }, form.id || undefined), "Imehifadhiwa.")}>Hifadhi</button></>}{<div className="admin-list">{rows.map((item: any) => <div className="admin-list-row" key={item.id}><div><strong>{item.title ?? item.name ?? "Bila kichwa"}</strong><small>{item.body ?? item.videoUrl ?? item.status ?? ""}</small></div>{!readOnly && <div className="table-actions"><button onClick={() => setForm({ ...form, ...item })}>Hariri</button><button onClick={() => onRun(() => adminDeleteCollectionItem(adminId, collectionName, item.id), "Imefutwa.")}><Trash2 size={14} /></button></div>}</div>)}{!rows.length && <Empty />}</div>}</section>; }
function CmsPanel({ values, setValues, onRun, adminId }: any) { return <section className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">PUBLIC SETTINGS</span><h2>Muonekano & CMS</h2></div></div><div className="form-grid">{[["systemName", "Jina la mfumo"], ["eyebrow", "Maneno ya juu"], ["headline", "Kichwa kikuu"], ["searchPlaceholder", "Ujumbe wa search"], ["whatsapp", "WhatsApp bila +"], ["owner", "Jina la mmiliki"], ["primaryColor", "Rangi kuu"], ["accentColor", "Rangi ya accent"]].map(([key, label]) => <Field key={key} label={label} value={values[key]} onChange={(value) => setValues({ ...values, [key]: value })} />)}</div><label className="control-field"><span>Maelezo</span><textarea value={values.description} onChange={(event) => setValues({ ...values, description: event.target.value })} /></label><label className="control-field"><span>Footer</span><textarea value={values.footer} onChange={(event) => setValues({ ...values, footer: event.target.value })} /></label><button className="admin-primary" onClick={() => onRun(() => adminSaveSiteSettings(adminId, values), "CMS settings zimehifadhiwa.")}>Hifadhi mabadiliko</button></section>; }
function MessagesPanel({ users, form, setForm, onRun, adminId }: any) { return <section className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">MESSAGING</span><h2>Tuma ujumbe</h2></div></div><div className="form-grid"><Field label="Subject" value={form.subject} onChange={(value) => setForm({ ...form, subject: value })} /><label className="control-field"><span>Kwa mtumiaji mmoja</span><select value={form.recipientId} onChange={(event) => setForm({ ...form, recipientId: event.target.value })}><option value="">Kwa wote</option>{users.map((item: any) => <option key={item.id} value={item.id}>{item.name ?? "Bila jina"} — {item.phone || item.email}</option>)}</select></label></div><label className="control-field"><span>Ujumbe</span><textarea value={form.body} onChange={(event) => setForm({ ...form, body: event.target.value })} /></label><button className="admin-primary" onClick={() => onRun(() => adminSaveCollectionItem(adminId, "messages", { ...form, broadcast: !form.recipientId, sentAt: new Date().toISOString() }), "Ujumbe umetumwa.")}>Tuma ujumbe</button></section>; }
function SecurityPanel({ isSuper, users, audit }: any) { return <div className="admin-two-col"><section className="admin-security-card"><ShieldCheck size={25} /><h2>{isSuper ? "Eneo la siri" : "Usalama wa admin"}</h2><p>{isSuper ? "Una access ya super_admin. Admin management, settings na audit logs zinapatikana." : "Admin wa kawaida hawezi kubadilisha super_admin au system security settings."}</p><div className="security-checks"><span>✓ Firebase Auth</span><span>✓ Role-based access</span><span>✓ Firestore Rules</span><span>✓ No passwords in Firestore</span></div></section><section className="admin-card"><h2>Audit summary</h2><p>Users: {users.length} · Admins: {users.filter((item: any) => ["admin", "super_admin"].includes(item.role)).length}</p><p>Audit actions: {audit.length}</p><small>Kwa custom claims, tumia Firebase Admin SDK katika mazingira ya privileged; frontend haiwezi kujipa role.</small></section></div>; }
function TransactionTable({ rows }: { rows: any[] }) { return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>REFERENCE</th><th>MTUMIAJI</th><th>MAELEZO</th><th>AINA</th><th>KIASI</th><th>BALANCE</th><th>TAREHE</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><code>{item.reference ?? item.id}</code></td><td>{item.userId}</td><td>{item.serviceName ?? item.description ?? "—"}</td><td><span className="pill">{item.type ?? (Number(item.amount) < 0 ? "DEBIT" : "CREDIT")}</span></td><td className={Number(item.amount) < 0 ? "amount-negative" : "amount-positive"}>{item.amount}</td><td>{item.previousBalance ?? "—"} → {item.newBalance ?? item.balanceAfter ?? "—"}</td><td>{dateText(item.createdAt)}</td></tr>)}</tbody></table>{!rows.length && <Empty />}</div>; }
function UserModal({ person, onClose }: { person: any; onClose: () => void }) { return <div className="admin-modal-backdrop" onClick={onClose}><div className="admin-modal" onClick={(event) => event.stopPropagation()}><button className="admin-modal-close" onClick={onClose}><X size={18} /></button><span className="admin-kicker">USER PROFILE</span><h2>{person.name ?? "Bila jina"}</h2><div className="profile-grid">{[["Phone", person.phone], ["Email", person.email], ["Username", person.username], ["Role", person.role], ["Account status", person.accountStatus ?? "active"], ["Verification", person.verificationStatus], ["Token balance", person.tokenBalance ?? 0], ["Total received", person.totalTokensReceived ?? 0], ["Total used", person.totalTokensUsed ?? 0], ["Registration", dateText(person.createdAt)], ["Last login", dateText(person.lastLoginAt)]].map(([label, value]) => <div key={String(label)}><small>{label}</small><strong>{String(value ?? "—")}</strong></div>)}</div><p className="privacy-note">Password za users hazihifadhiwi wala hazionyeshwi kwenye dashboard.</p></div></div>; }
